### GET Single Product
GET http://localhost:8081/products/d608d667-08c8-41e3-a7b0-0f23201ed6e4 HTTP/1.1

### POST Create Product
POST http://localhost:8081/products HTTP/1.1
Content-Type: application/json

{
    "name": "Product 1",
    "price": 10
}

### PUT Update Product
PUT http://localhost:8081/products/d608d667-08c8-41e3-a7b0-0f23201ed6e4 HTTP/1.1
Content-Type: application/json

{
    "name": "Product 1",
    "price": 10
}

